### ISSUE TITLE
Why using Swish activation can't save model?

### ISSUE THREAD

**Issue by DavidLanz** [shahariarrabby/Mnist_cnn_Swish#1]
model.save('0.99671.h5')

->

AttributeError: 'Activation' object has no attribute '__name__'

**Comment by vaishnavm217** [comment]
Even I am suffering the same issue

**Comment by avenash97** [comment]
get_custom_objects().update({'swish': swish}) is the way to go instead of get_custom_objects().update({'swish': Activation(swish )}).

**Comment by ShahariarRabby** [comment]
Please Follow @avenash97 
Thanks @avenash97
